export const defaultGeneralSettings = {
  defaultSourceResultLimit: 8,
  cachingEnabled: true,
  allowWebFallback: true,
  fallbackDomainAllowlist: ["quran.com", "sunnah.com"],
  similarityThreshold: 0.45,
  sourceTimeoutMs: 7000,
  translationTimeoutMs: 6000,
  topicsList: [
    "zzGeneral",
    "Allah / Tawhid",
    "Prophethood",
    "Qur'an",
    "Sunnah",
    "Aqidah / Belief",
    "Worship and Practice",
    "Christianity / Jesus",
    "Science and Reason",
    "Women and Family",
    "Jihad and Misconceptions",
    "Afterlife and Salvation",
    "Personal Doubts / Guidance",
  ],
  audienceTypeList: [
    "General",
    "Seeker",
    "Christian / Jesus-focused",
    "Jewish",
    "Non-Muslim / Interfaith",
    "Skeptic / Atheist",
    "Critical / Challenging",
    "Muslim / Doubting",
  ],
  questionTypeList: [
    "Clarification",
    "Comparative",
    "Evidential",
    "Textual",
    "Theological",
    "Historical",
    "Ethical / Social",
    "Challenging / Critical",
  ],
  difficultyList: [
    "Easy",
    "Medium",
    "Advanced",
    "Hard",
  ],
  likelyIntentList: [
    "Seek understanding",
    "Seeking proof",
    "Seeking conviction",
    "General curiosity",
    "Clarification",
    "Challenge",
    "Critical inquiry",
    "Personal guidance",
    "Needs review",
  ],
};

const nowIso = new Date().toISOString();

export const defaultAiProviders = [
  {
    providerId: "ai-mock-local",
    name: "Mock Local AI",
    providerType: "other",
    enabled: true,
    baseUrl: "",
    apiKeyRef: "",
    modelOptions: [
      {
        modelId: "mock-da'wah-desk-v1",
        label: "Mock Stable Workflow",
        enabled: true,
        supportsStructuredOutput: true,
        supportsToolUse: false,
        supportsReasoning: true,
        notes: "Local heuristic provider for safe prototype development.",
      },
      {
        modelId: "mock-da'wah-desk-fast",
        label: "Mock Fast Drafting",
        enabled: true,
        supportsStructuredOutput: true,
        supportsToolUse: false,
        supportsReasoning: false,
        notes: "Lower-friction mock model for quick drafting tests.",
      },
    ],
    defaultModelId: "mock-da'wah-desk-v1",
    headers: {},
    notes: "Built-in local mock provider used by default until real credentials are configured.",
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    providerId: "ai-vertex-primary",
    name: "Google Vertex AI",
    providerType: "vertex-ai",
    enabled: true,
    baseUrl: "https://aiplatform.googleapis.com",
    apiKeyRef: "VERTEX_AI_SERVICE_ACCOUNT_PATH",
    projectId: "",
    location: "global",
      modelOptions: [
        {
          modelId: "gemini-3.5-flash",
          label: "Gemini 3.5 Flash (Vertex)",
          enabled: true,
          supportsStructuredOutput: true,
          supportsToolUse: false,
          supportsReasoning: true,
        },
        {
          modelId: "gemini-3.1-flash-lite",
          label: "Gemini 3.1 Flash Lite (Vertex)",
          enabled: true,
          supportsStructuredOutput: true,
          supportsToolUse: false,
          supportsReasoning: true,
        },
        {
          modelId: "gemini-2.5-flash",
          label: "Gemini 2.5 Flash (Vertex)",
          enabled: true,
          supportsStructuredOutput: true,
          supportsToolUse: false,
          supportsReasoning: true,
        },
        {
          modelId: "gemini-2.5-pro",
          label: "Gemini 2.5 Pro (Vertex)",
          enabled: true,
          supportsStructuredOutput: true,
          supportsToolUse: false,
          supportsReasoning: true,
        },
      ],
    defaultModelId: "gemini-2.5-flash",
    headers: {},
    notes: "Server-side Vertex AI provider using service account authentication. Project ID is read from the saved credential file. Uses the global model endpoint because current Gemini model availability is broader there than in me-central1.",
    createdAt: nowIso,
    updatedAt: nowIso,
  },
];

export const defaultAiDefaults = {
  defaultProviderId: "ai-vertex-primary",
  defaultModelId: "gemini-2.5-flash",
};

export const defaultSessionAiSelections = {
  "local-session": {
    sessionId: "local-session",
    providerId: "ai-vertex-primary",
    modelId: "gemini-2.5-flash",
    inheritedFromDefault: true,
    updatedAt: nowIso,
  },
};

export const defaultConnectors = [
  {
    connectorId: "conn-quran-primary",
    name: "Quran Foundation Adapter",
    category: "quran",
    enabled: true,
    connectionType: "api",
    baseUrl: "https://apis.quran.foundation",
    apiKeyRef: "",
    headers: {},
    params: {
      environment: "production",
      authBaseUrl: "https://oauth2.quran.foundation",
      language: "Arabic",
    },
    trustTier: 1,
    notes: "Uses Quran Foundation production OAuth2 and Content/Search APIs.",
  },
  {
    connectorId: "conn-hadith-en",
    name: "Sunnah English Adapter",
    category: "hadith-en",
    enabled: true,
    connectionType: "api",
    baseUrl: "TODO_HADITH_EN_PROVIDER_URL",
    apiKeyRef: "",
    headers: {},
    params: { language: "English" },
    trustTier: 1,
    notes: "Reserved slot for a future dedicated Sunnah English API connector.",
  },
  {
    connectorId: "conn-hadith-ar",
    name: "Sunnah Arabic Adapter",
    category: "hadith-ar",
    enabled: true,
    connectionType: "api",
    baseUrl: "TODO_HADITH_AR_PROVIDER_URL",
    apiKeyRef: "",
    headers: {},
    params: { language: "Arabic" },
    trustTier: 1,
    notes: "Reserved slot for a future dedicated Sunnah Arabic API connector.",
  },
  {
    connectorId: "conn-approved-other",
    name: "Approved Sources Adapter",
    category: "other",
    enabled: true,
    connectionType: "manual",
    baseUrl: "",
    apiKeyRef: "",
    headers: {},
    params: {},
    trustTier: 2,
    notes: "Manual adapter for approved non-Quran and non-Sunnah sources.",
  },
  {
    connectorId: "conn-web-fallback",
    name: "Controlled Web Fallback",
    category: "web",
    enabled: true,
    connectionType: "web",
    baseUrl: "",
    apiKeyRef: "",
    headers: {},
    params: {},
    trustTier: 4,
    notes: "Approved-domain fallback adapters for Quran.com and Sunnah.com. Only domains in the allowlist are used.",
  },
];

export const backendSeedCases = [];

export const backendSeedBites = [];

export const backendSeedSources = [];

export const defaultRuntimeState = {
  connectors: defaultConnectors,
  aiProviders: defaultAiProviders,
  sessionAiSelections: defaultSessionAiSelections,
  settings: {
    general: defaultGeneralSettings,
    aiDefaults: defaultAiDefaults,
  },
  savedCases: backendSeedCases,
  savedBites: backendSeedBites,
  sourceRecords: backendSeedSources,
};

